#!/bin/sh

bspc monitor -d 0 1 2 3 4
bspc config window_gap 5
bspc config focus_follows_pointer true
bspc config border_width 2
bspc config focused_border_color "#ffffff"

sh ~/.fehbg

sxhkd &
polybar -r base &
dunst &
