#!/bin/sh

bspc monitor -d 0 1 2 3 4
bspc config window_gap 5
bspc config focus_follows_pointer true
bspc config border_width 3
bspc config focused_border_color "#2aa198"

xset s off -dpms
xmodmap ~/.Xmodmap
sh ~/.fehbg

sxhkd &
polybar -r base &
dunst &

bspc rule -a scratchpad sticky=on state=floating hidden=on
xterm -class scratchpad -geometry 70x5 &
